# Generated by Django 3.0.4 on 2020-04-01 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.IntegerField(default=101)),
                ('book_date', models.DateField()),
                ('booked', models.IntegerField(default=1)),
                ('name', models.CharField(default='Nobody', max_length=20)),
            ],
        ),
    ]
