# Generated by Django 3.0.4 on 2020-03-28 18:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='email',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='book_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='booked',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(default='Nobody', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='room',
            field=models.IntegerField(default=101),
        ),
    ]
