# Generated by Django 3.0.4 on 2020-03-28 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0002_auto_20200328_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='book_date',
            field=models.DateTimeField(default='2020-03-20'),
        ),
    ]
