# Generated by Django 3.0.4 on 2020-03-28 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0003_auto_20200329_0004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='book_date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='booked',
        ),
        migrations.RemoveField(
            model_name='article',
            name='name',
        ),
        migrations.RemoveField(
            model_name='article',
            name='room',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='david', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='the secret', max_length=100),
        ),
    ]
