# Generated by Django 3.0.4 on 2020-03-28 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0004_auto_20200329_0025'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AddField(
            model_name='article',
            name='book_date',
            field=models.DateTimeField(default='2020-03-20'),
        ),
        migrations.AddField(
            model_name='article',
            name='booked',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='name',
            field=models.CharField(default='Nobody', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='room',
            field=models.IntegerField(default=101),
        ),
    ]
