# Generated by Django 3.0.4 on 2020-03-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0006_auto_20200329_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='book_date',
            field=models.DateField(default='2020-03-20'),
        ),
    ]
