# Generated by Django 3.0.4 on 2020-03-28 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0008_auto_20200329_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='book_date',
            field=models.DateField(),
        ),
    ]
